### PR TITLE
Added Makefile and Github Workflow

### PR DESCRIPTION
**Pull request by Noriskky**
Hey i added a Makefile to make it more straight forward build/compile the project also i added the Documentation for that.

The Last thing i did is adding a Github Workflow that executes everytime you commit/push and you accept Pullrequests
it will build the project for you, this can useful so your users dont have to compile it from source everytime they want a newer version and you can provide download of the jars automactilly.

\- Noriskky

### CODE REVIEW

**Comment by Zergatul** [comment]
Thanks for proposal. I never worked with github actions. I have few questions:
- Who will pay for CPU time if bad actors will spam pull requests?
- How makefile is better than gradle?
- I checked your fork, and I don't see where I can download jars. Also fabric creates 2 jars, it may be good to exclude sources jar, since it may confuse most people.

**Comment by Noriskky** [comment]
Hey no problem i can fix the Issues you proposed just give me like 10 minutes

**Comment by Noriskky** [comment]
Hey 
1. I Fixed the Issues with the Spamming also i added documenation where to find the jars
2. I find it a bit easier to follow the instruction with Makefiles also you can intregrade it better in your Workflow with for example Neovim/Vim 
3. I now exclude the sources jar

\- Noriskky

**Comment by Noriskky** [comment]
PS: The picture in the Readme will work when the pullrequest is accepted

**Comment by Zergatul** [comment]
> I find it a bit easier to follow the instruction with Makefiles also you can intregrade it better in your Workflow with for example Neovim/Vim

Maybe it can be better with Neovim, but almost everyone in Minecraft modding community uses Intellij IDEA. And it works perfectly fine with gradle.

And from the other side, having makefile on top of gradle doesn't really simplify things. Now you need to understand 2 build tools instead of one, and you can have issues in 2 places instead of 1.

Could you also update README, on Windows it is not required to type `gradlew.bat`, it understands `gradlew build` perfectly fine. Even from powershell I always use `./gradlew build`.

**Comment by Noriskky** [comment]
I fully understand you and i can change it shortly

**Comment by Zergatul** [comment]
Did you actually test jar file built by github actions?

**Comment by Noriskky** [comment]
Yes

**Pull request merged**
